name: Upload to S3

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync logs to S3
      run: |
        aws s3 sync logs s3://lowprice-dbt-test/logs --delete
    
    - name: Sync lowprice to S3
      run: |
        aws s3 sync lowprice s3://lowprice-dbt-test/lowprice --delete